Chore/bump nexus 2.6.9
sirclo-solution/template-rose pull request #12
Opened 2022-06-21 09:34 UTC by falmesino

```
Chore/bump nexus 2.6.9
- bump nexus version from 2.5.3 to 2.6.9
- add shipping locales
- style input qty
- style discount note
- add and style buyer note input for each item in CartDetails and OrderSummaryBox
```

URL PR: TBA
URL Task: https://phabricator.sirclo.com/T33595
Pull Latest: OK
Build (Local): Failed, tapi sepertinya di harbormaster akan aman

***

**Screenshots (CartDetails) **

![Screen Shot 2022-06-21 at 16 27 29](https://user-images.githubusercontent.com/1308515/174767629-598add51-3d80-4306-8829-cb24e9d115fb.png)
![Screen Shot 2022-06-21 at 16 27 34](https://user-images.githubusercontent.com/1308515/174767643-c48c6746-bf8c-4bb3-b86b-bf4c1107dace.png)
![Screen Shot 2022-06-21 at 16 27 36](https://user-images.githubusercontent.com/1308515/174767653-a981cc95-fe59-4c8a-89ad-13393988c9b2.png)
![Screen Shot 2022-06-21 at 16 27 39](https://user-images.githubusercontent.com/1308515/174767665-d983b21a-7c81-4075-9b63-4e464688afcc.png)

**Screenshots (OrderSummaryBox)**
![Screen Shot 2022-06-21 at 16 26 28](https://user-images.githubusercontent.com/1308515/174767861-e8c77e86-ff73-43e6-9f51-31c8b799b4cb.png)
![Screen Shot 2022-06-21 at 16 26 32](https://user-images.githubusercontent.com/1308515/174767880-ae6a825e-8737-4683-9c80-026b478a683a.png)
![Screen Shot 2022-06-21 at 16 26 37](https://user-images.githubusercontent.com/1308515/174767889-43a79852-4dd0-4e64-b90e-fecaa1896666.png)
![Screen Shot 2022-06-21 at 16 26 40](https://user-images.githubusercontent.com/1308515/174767895-1832cc49-ac75-4ca4-a66c-1e9190350a33.png)

2022-06-21 09:51 UTC, rhmnaulia approved these changes

2022-06-22 02:25 UTC, virginiaritonga approved these changes

2022-06-22 09:52 UTC, inezamandha requested changes

2022-06-22 09:52 UTC, inezamandha commented on components/OrderSummaryBox/index.tsx
> +*/
ini diperluin gak ya mang? soalnya di comment

2022-06-22 09:52 UTC, inezamandha commented on components/OrderSummaryBox/index.tsx
> +						withSeparatedVariant
ini ke tab ya mang?

2022-06-22 09:52 UTC, inezamandha commented on components/OrderSummaryBox/index.tsx
> +						removeIcon={<IoTrashBinOutline />}
ini juga yaah?

2022-06-22 09:52 UTC, inezamandha commented on components/OrderSummaryBox/index.tsx
> +						  )
ini ke tab apa emang begini yaa mang?

2022-06-22 09:55 UTC, falmesino commented on components/OrderSummaryBox/index.tsx
> +						  )
sudah dirapiken, abis ngurutin props-nya biar sama kaya yang di cart

2022-06-22 09:56 UTC, falmesino commented on components/OrderSummaryBox/index.tsx
> +*/
sudah dihapus

2022-06-22 09:59 UTC, inezamandha approved these changes

2022-06-22 10:00 UTC, rhmnaulia approved these changes

2022-06-22 10:02 UTC, mayun19 requested changes
mang otoy, di figma ada label "Catatan untuk penjual". ini belum ditambahan kah(?)

2022-06-22 10:54 UTC, mayun19 approved these changes

2022-06-23 03:11 UTC, merged