chore: bump version 2.8.2
sirclo-solution/template-rose pull request #13
Opened 2022-06-23 11:10 UTC by feliciakri

**[x] Implementasi Payment Confirmation [figma disini](https://www.figma.com/file/cl2GPB5tKKSNjA5CxPsJBB/%5BVENDOR%5D-Ros%C3%A9?node-id=1030%3A3574)**
Payment confirmation (ada banyak browser limitation untuk styling, sehingga tidak bisa sama persis figma untuk padding dan margin)
![image](https://user-images.githubusercontent.com/8079082/175284195-7f7092ac-befb-4c9e-9c3b-02da773f76f6.png)
![image](https://user-images.githubusercontent.com/8079082/175284221-68204dce-88c0-4c7b-9889-1a6550f85565.png)

**[x] Implementasi Product Card [figma disini](https://www.figma.com/file/cl2GPB5tKKSNjA5CxPsJBB/%5BVENDOR%5D-Ros%C3%A9?node-id=2104%3A3216)**  
Product card
di homepage
![image](https://user-images.githubusercontent.com/8079082/175283185-eef9b51a-12ef-4119-9ef2-305da5718075.png)
di products
![image](https://user-images.githubusercontent.com/8079082/175283263-47c8f462-e9c3-4c10-ad0e-4b451a5e5aa0.png)

**[x] Fix flipImage and quickView Feature issue** quickView tidak ada di Rose (sudah tanya designer)   
https://user-images.githubusercontent.com/8079082/175284726-cad9b0f3-1628-439d-8cf7-cf8704f8ba06.mp4

**[x] add published and isActive filter to lookbook and blog single dan juga emptyComponent di blogSingle seperti yang ada di sini https://phabricator.sirclo.com/D38355**  
![image](https://user-images.githubusercontent.com/8079082/175284770-be367f8b-0e28-4610-ad6d-2d4e178799c3.png)
![image](https://user-images.githubusercontent.com/8079082/175285562-b408d02f-c6ec-4299-b2c3-c5e47467e16a.png)

2022-06-23 11:16 UTC, falmesino commented on pages/[lng]/blog/index.tsx
>  import { useI18n, Blogs, BlogCategories, getBlogHeaderImage, isBlogAllowed } from '@sirclo/nexus'
```suggestion
import { 
  IoChevronBack,
  IoChevronForward,
  IoHelpCircle
} from 'react-icons/io5'
import { 
  useI18n,
  Blogs,
  BlogCategories,
  getBlogHeaderImage,
  isBlogAllowed 
} from '@sirclo/nexus'
```

Berdasarkan adat istiadat warga setempat, jika improt-nya ada lebih dari dua dibikin ke bawah seperti contoh di atas.

2022-06-23 11:17 UTC, falmesino commented on pages/[lng]/lookbook/categories/[slug].tsx
>  import { isLookbookAllowed, LookbookSingle, useI18n, Products } from '@sirclo/nexus'
```suggestion
import { 
  isLookbookAllowed,
  LookbookSingle,
  useI18n, 
  Products 
} from '@sirclo/nexus'
```

dibuat ke bawah seperti tjontoh karena improt-nya ada lebih dari dua.

2022-06-23 11:20 UTC, falmesino commented on public/scss/pages/PaymentNotif.module.scss
> +        border: none;
```suggestion
        content: " ";
        
        @include typographyBuilder(secondary, 400, 12, 16);
        width: 17px;
        margin-right: 5px;
```

per-include-an taro paling atas dan setelah content (kecuali yang svgIcon gpp taro bawah aja)

2022-06-23 11:21 UTC, falmesino commented on public/scss/pages/PaymentNotif.module.scss
> +      }
```suggestion
      &::placeholder
      {
        color: $color_text_placeholder !important;
        opacity: 1; /* Firefox */
      }
      
      &:-ms-input-placeholder,
      &::-ms-input-placeholder 
      { 
        /* Internet Explorer 10-11 */
        color: $color_text_placeholder !important;
      }
```

dibegitukan

2022-06-23 11:22 UTC, falmesino requested changes
ada beberapa komeng

2022-06-24 03:01 UTC, virginiaritonga requested changes

2022-06-24 03:01 UTC, virginiaritonga commented on pages/[lng]/payment_notif/[[...orderID]].tsx
> +  checkPaymentOrderInputContentClassName: `${styleForm.form} ${styles.paymentNotif_formInput} "check123"`,
"check123" kepake kah?

2022-06-24 03:06 UTC, virginiaritonga commented
minta tolong attach tampilan Payment confirmation di mozilla + chrome (+ safari kalau bisa), krn kmrn sempet ada issue button No File Chosen / Choose File yang berantakan di beberapa browser

2022-06-24 04:00 UTC, sultanfariz approved these changes

2022-06-24 04:26 UTC, virginiaritonga approved these changes

2022-06-24 04:31 UTC, falmesino approved these changes

2022-06-24 06:41 UTC, merged