add webvitals tracker, map pin point, buyerHideNameSliderClassName, fix maintenance page, remove ts-ignore
sirclo-solution/template-rose pull request #22
Opened 2022-07-14 10:38 UTC by ekkyregita

Map pin point 

-account
![image](https://user-images.githubusercontent.com/108525079/178962170-a1c5891c-3981-40df-8674-f07719ad3315.png)

-place order
![image](https://user-images.githubusercontent.com/108525079/178962756-9fadda2d-a90e-4ef7-b695-e63944028aa5.png)

-shpping method
![image](https://user-images.githubusercontent.com/108525079/178963155-c6314a10-5bb4-437f-86c9-667bf5238dc8.png)

Webvitals tracker
![image](https://user-images.githubusercontent.com/108525079/178963470-4fd773fc-59a0-446a-991a-a0ded5aaf8fc.png)
![image](https://user-images.githubusercontent.com/108525079/178963524-6fc5eaa4-047f-4529-bb17-405ac6685246.png)

Maintenance page

-default
![image](https://user-images.githubusercontent.com/108525079/178961799-daa7c1e0-6da1-4c19-849e-0dd05dcfb92b.png)

-custom
![image](https://user-images.githubusercontent.com/108525079/178961651-15d5810a-d304-461f-b9a5-a4a5983c1da2.png)

2022-07-14 10:51 UTC, falmesino requested changes

2022-07-14 10:51 UTC, falmesino commented on public/scss/components/CustomerDetail.module.scss
> +    @include absolute(50%,auto,auto,50%);
```suggestion
    @include absolute(50%, auto, auto, 50%);
    
    transform: translate3d(-50%, -50%, 0); // tambahin ini biar icon map pin point-nya jadi ke tengah
```
tiap parameter mixin, pisahin pake spasi

2022-07-14 10:51 UTC, falmesino commented on public/scss/components/Map.module.scss
> +    @include absolute(50%,auto,auto,50%);
```suggestion
    @include absolute(50%, auto, auto, 50%);
    
    transform: translate3d(-50%, -50%, 0); // tambahin ini biar icon map pin point-nya jadi ke tengah
```
tiap parameter mixin, pisahin pake spasi

2022-07-14 10:57 UTC, feliciakri commented
Untuk commit message mengikuti convention ini yaa: https://www.conventionalcommits.org/en/v1.0.0/

Untuk yang map pin point bisa tidak diperbaiki positioning nya?
![image](https://user-images.githubusercontent.com/8079082/178967322-9809323d-cd16-4f48-963a-249bf202b690.png)
![image](https://user-images.githubusercontent.com/8079082/178967358-eb1cfd7f-2cff-417a-9960-1937d4facdd9.png)

2022-07-14 10:59 UTC, feliciakri commented
terus dari figma map pin pointnya ada style sendiri nihh boleh di ceki ceki yaa https://www.figma.com/file/cl2GPB5tKKSNjA5CxPsJBB/%5BVENDOR%5D-Ros%C3%A9?node-id=1001%3A3940
![image](https://user-images.githubusercontent.com/8079082/178967694-23d77e9f-07bd-4d30-b3c7-bf0b8a8ee1d5.png)

2022-07-14 11:03 UTC, ekkyregita commented
@feliciakri okay noted kak feli, untuk positioning itu yg mana ya kak ?

2022-07-15 02:46 UTC, Sukmaarifin approved these changes

2022-07-15 03:11 UTC, inezamandha commented
halo ekky maaf ya ikut nimbrung, aku lihat maintenance pagenya belum sesuai sama di template lain untuk classnamenya

bisa dicoba cek seharusnya ada penambahan seperti title dan info

<img width="355" alt="image" src="https://user-images.githubusercontent.com/45808774/179142204-525add11-401f-4669-94a1-2c45659eb6aa.png">

saat ini tampilannya kan kayak gini ya dari kamu, bisa tolong tanyakan ke desainer juga yaa misal `font` nya yang benar seperti apa atau margin paddingnya gitu yaa biar rapi. memang kalau aku lihat di figmanya belum ada (enggak seperti template lain)

<img width="111" alt="image" src="https://user-images.githubusercontent.com/45808774/179142324-085d4f48-c109-43f9-9ae3-0e761d34fa5e.png">

2022-07-15 03:14 UTC, inezamandha commented
seperti kata kakak kakak lain, mapsnya tolong disesuaikan dengan figma yaa

nah tapi kalau tambahan dari aku
- tolong lengkapin localesnya yaa

contoh:

2022-07-15 03:22 UTC, inezamandha requested changes

2022-07-15 03:22 UTC, inezamandha commented on pages/_app.js
>  }
bisa ditambahkan seperti komen komen yang aku bilang yaah

2022-07-15 10:37 UTC, ekkyregita commented
map position & searchbar placeholder :
- account
![image](https://user-images.githubusercontent.com/108525079/179206306-66137235-791f-4544-b488-8daed6ad88b3.png)

- place order
![image](https://user-images.githubusercontent.com/108525079/179206670-6892042f-6665-4bbf-a44b-4f995f50b730.png)

- shipping method
![image](https://user-images.githubusercontent.com/108525079/179206961-254d1be8-36b1-40c4-a525-ca69a0495142.png)


maintenance mode :
![image](https://user-images.githubusercontent.com/108525079/179205869-06d0661f-49f2-4740-8cfb-be17a82a1ccf.png)

sudah saya update yaa kakak-kakak @inezamandha @feliciakri @mayun19 @falmesino

2022-07-15 10:58 UTC, falmesino requested changes

2022-07-15 10:58 UTC, falmesino commented on public/scss/components/Maintenance.module.scss
> +      order: 2 !important;
```suggestion
      @include typographyBuilder(secondary, 400, 20, 24),
      margin-bottom: 8px !important;
      max-width: 100% !important;
      order: 2 !important;
```

kenapa tydac pakay pake mixin?
trus !important-nya kok banyak yak, kenapa ini?

2022-07-15 10:58 UTC, falmesino commented on public/scss/components/Maintenance.module.scss
> +      order: 3 !important;
sama kayak di atas, kenapa ga pakay mixin sama kenapa !important-nya banyak

2022-07-15 11:00 UTC, ekkyregita commented on public/scss/components/Maintenance.module.scss
> +      order: 2 !important;
ketimpa sama inline style kak, tadi aku coba jadi ga kebaca kalau pake mixin

2022-07-18 06:12 UTC, falmesino approved these changes

2022-07-18 06:29 UTC, merged