feat: moreShipping, shipperLogo
sirclo-solution/template-rose pull request #33
Opened 2022-09-13 07:19 UTC by DiebrataA

![fb_login](https://user-images.githubusercontent.com/38358288/189836239-87ad21a9-4532-4be1-a2cb-034893b8d6fa.png)
![moreShipping](https://user-images.githubusercontent.com/38358288/189836254-ca4c76fa-52e1-4985-9880-bb3b4ac535b5.png)
![shippingLogo](https://user-images.githubusercontent.com/38358288/189836257-d3ed11be-8c3d-4372-8325-64c7d35c7d0b.png)

2022-09-13 08:17 UTC, Sukmaarifin approved these changes

2022-09-13 09:47 UTC, inezamandha commented
itu sebelah kiri ada google buttonnya malahan yang error yang gamuncul yaa? atau karena belum disetup(?) dan harusnya kehide yaa? apa di task baru saja ya karena bukan di sini?

2022-09-13 09:47 UTC, inezamandha commented
ada lagi enggak di halaman payment gitu voucherShipperLogo nya biar samaan di bawah voucherBankLogo?

2022-09-13 10:49 UTC, DiebrataA commented
> itu sebelah kiri ada google buttonnya malahan yang error yang gamuncul yaa? atau karena belum disetup(?) dan harusnya kehide yaa? apa di task baru saja ya karena bukan di sini?

iyak kalo ini spertinya karena dijalanin via localhost kali ya, soalnya di staging udah aman aja nezz, kemarin2 udah di testi juga sii

2022-09-13 10:50 UTC, DiebrataA commented
> ada lagi enggak di halaman payment gitu voucherShipperLogo nya biar samaan di bawah voucherBankLogo?

oiya halaman lainnya soon akan kuupdate mungkin besok ya nezz

2022-09-14 01:37 UTC, sultanfariz commented
Mo tanya, buat kupon yang both shipping sama payment ngga dibikin satu row aja?
Referensinya diff ini:
https://phabricator.sirclo.com/D46009 (LASTINO)
https://phabricator.sirclo.com/D45986 (MERLIN)
https://phabricator.sirclo.com/D45999 (UNO)

2022-09-14 01:37 UTC, sultanfariz approved these changes

2022-09-14 02:14 UTC, inezamandha commented
nah iya buat yang satu row itu maksudnya ke samping samping gitu kan yaa? antara bank sama shipping?

tak kirain iyak atas bawah saja gitu karena gapossible samping sampingan, tapi ternyata possible yessh

ku sedang bantu tanyakeun ke desainer dulu waktu itu desainer kirain juga ngira gabisa samping2an atau satu row (tapi kekuatan mamang bisa ya) hahaha

**punyaku diffnya juga masih pending inii

2022-09-14 03:56 UTC, inezamandha commented
tadi sudah tanya ke desainer katanya akhirnya disamping sampingkan yaak~

2022-09-14 03:57 UTC, inezamandha requested changes
commentnya yang di atas atas yaaw

2022-09-14 08:32 UTC, inezamandha requested changes

2022-09-14 08:32 UTC, inezamandha commented on public/scss/components/OrderSummaryBox.module.scss
> +        max-width: calc(100% + (12px * 2));
bisa pakai mixin yang fixedWidth seperti di atas enggak yaah?

2022-09-14 08:32 UTC, inezamandha commented on public/scss/components/OrderSummaryBox.module.scss
> +        justify-content: left;
ini bisa pakai mixin tidak ya?

2022-09-14 08:32 UTC, inezamandha commented on public/scss/components/OrderSummaryBox.module.scss
> +            max-height: 15px;
boleh pakai mixin fixedHeight?

2022-09-14 08:32 UTC, inezamandha commented on public/scss/components/OrderSummaryBox.module.scss
> +            line-height: 16px;
ada mixin typographyBuilder enggak yaa? (tapi berarti mesti tau fontweight)

2022-09-14 08:32 UTC, inezamandha commented on public/scss/components/OrderSummaryBox.module.scss
> +        max-width: calc(100% + (12px * 2));
boleh pakai mixin fixedWidth?

2022-09-14 08:32 UTC, inezamandha commented on public/scss/components/OrderSummaryBox.module.scss
> +        padding: 12px 12px;
boleh dijadikan padding: 12px ?

2022-09-14 08:36 UTC, inezamandha requested changes

2022-09-14 08:36 UTC, inezamandha commented on public/scss/components/OrderSummaryBox.module.scss
> +        height: 12px;
biar sama rata kayak yang sebelumnya udah kamu buat, apa baiknya widthnya enggak dihapus atau disesuaikan juga biar rapi?

kalau skrg kan begini (baris/kolomnya jadi enggak sama rata)
<img width="426" alt="image" src="https://user-images.githubusercontent.com/45808774/190104056-0b79c608-751d-4592-acd8-0f6b4fd980b1.png">

yang kemarin kamu ss sudah rapi macam begini (tapi aku gapunya ss nya)
<img width="537" alt="image" src="https://user-images.githubusercontent.com/45808774/190104417-b7b6e1a9-0e29-40a4-a834-430a1b2ad8e2.png">

2022-09-14 10:00 UTC, inezamandha approved these changes

2022-09-14 10:02 UTC, merged