feat: coupon improvement 2.16.1
sirclo-solution/template-rose pull request #36
Opened 2022-10-24 02:27 UTC by virginiaritonga

2022-10-25 11:06 UTC, falmesino requested changes

2022-10-25 11:06 UTC, falmesino commented on public/scss/components/OrderSummaryBox.module.scss
> +        margin: 0;
```suggestion
            width: 100%;
            max-width: 1170px; 
            margin: 0;

```

indent-nya kurang nih nyonya

2022-10-25 11:06 UTC, falmesino commented on public/scss/components/OrderSummaryBox.module.scss
> +        max-height: 80vh;;
```suggestion
        max-height: 80vh;

```

titik koma-nya kebanyakan

2022-10-25 11:06 UTC, falmesino commented on public/scss/components/OrderSummaryBox.module.scss
> +        @include typographyBuilder(secondary,400,12,16);
```suggestion
        @include typographyBuilder(secondary, 400, 12, 16);

```

kasih spasi

2022-10-25 11:06 UTC, falmesino commented on public/scss/components/OrderSummaryBox.module.scss
> +        border: none;
```suggestion
        border: none;

```

hapus enternya

2022-10-25 11:59 UTC, sultanfariz commented
terms and condition kupon kelebihan padding sama list stylenya ngga decimal
![image](https://user-images.githubusercontent.com/55394860/197767447-decd669d-673b-40bf-a6a8-04bdc8c966b9.png)

2022-10-26 01:24 UTC, mayun19 commented
warna button disable "gunakan" berbeda dengan yg ada di figma 
> <img alt="Screen Shot 2022-10-25 at 16 45 25" width="1280" src="https://user-images.githubusercontent.com/43097333/197754938-33280b5b-00fe-4c31-b55b-a6398023483e.png">
> 

**figma** 
![image](https://user-images.githubusercontent.com/16263184/197912653-0d5b7a1b-08df-4e41-be88-dba452db032c.png)

2022-10-26 01:49 UTC, mayun19 requested changes

2022-10-26 01:49 UTC, mayun19 commented on components/OrderSummaryBox/index.tsx
> +              // voucherTitleClassName: `${styleOrderSummary.orderSummary_voucherTitle} ${lng}`,
ini lupa dihapus kah?

2022-10-26 01:49 UTC, mayun19 commented on public/scss/components/OrderSummaryBox.module.scss
> +        outline: 0;
bisa diseragamkan dg outline: none ?

2022-10-26 01:49 UTC, mayun19 commented on public/scss/components/OrderSummaryBox.module.scss
> +        border: 0;
bisa diseragamkan dg border: none ?

2022-10-26 01:49 UTC, mayun19 commented on public/scss/components/OrderSummaryBox.module.scss
> +        @include typographyBuilder(secondary,400,14,24);
ini dikasih spasi juga

@include typographyBuilder(secondary, 400, 14, 24);

2022-10-26 03:35 UTC, virginiaritonga commented
updated styling:

- disabled button

  <img width="1228" alt="Screen Shot 2022-10-26 at 10 19 22" src="https://user-images.githubusercontent.com/43097333/197928449-823d3790-6bca-4513-ba9b-2f1d5a2914d7.png">

- terms condition list
  <img width="480" alt="Screen Shot 2022-10-26 at 09 46 00" src="https://user-images.githubusercontent.com/43097333/197928520-c0ff4733-c285-46c9-826a-b701ed3ffee0.png">

2022-10-26 03:41 UTC, falmesino approved these changes

2022-10-26 03:54 UTC, mayun19 approved these changes

2022-10-26 04:06 UTC, sultanfariz approved these changes

2022-10-26 04:18 UTC, merged