fix(order-summary): styling popup point
sirclo-solution/template-rose pull request #74
Opened 2023-05-24 07:18 UTC by ardiankristo

Figma:
https://www.figma.com/file/srLjsAPJpqwO1MFnOgDWk2/Rose-v.02?type=design&node-id=1401-8723&t=mI29XLRgutVQX3RL-0

**[ID]**
Applied point:
![Screenshot from 2023-05-24 14-13-11](https://github.com/sirclo-solution/template-rose/assets/40454642/c3f2fd2a-6cbb-433e-9e2d-c215e17e0b7f)
![Screenshot from 2023-05-24 14-14-40](https://github.com/sirclo-solution/template-rose/assets/40454642/2c633f8a-237a-473b-a9af-b27c83e4bcf4)

Point popup:
![Screenshot from 2023-05-24 14-13-15](https://github.com/sirclo-solution/template-rose/assets/40454642/47dad1bd-14f1-4285-a5b6-ebbf293c7099)
![Screenshot from 2023-05-24 14-14-52](https://github.com/sirclo-solution/template-rose/assets/40454642/903d28c1-8fcc-4bfb-9d48-a018caeee998)

Insufficient point:
![Screenshot from 2023-05-24 14-13-18](https://github.com/sirclo-solution/template-rose/assets/40454642/300a4115-5b7f-4340-9599-6983640b6c7b)
![Screenshot from 2023-05-24 14-15-06](https://github.com/sirclo-solution/template-rose/assets/40454642/f5e0745a-5819-4162-b590-6fdf4737edba)

**[EN]**
Applied point:
![Screenshot from 2023-05-24 14-25-04](https://github.com/sirclo-solution/template-rose/assets/40454642/0033bc3f-8011-4938-89c0-bcc5abeb48c4)
![Screenshot from 2023-05-24 14-25-15](https://github.com/sirclo-solution/template-rose/assets/40454642/d11de98a-a4d6-4af9-8fd9-2d42ae3c8f18)

Point popup:
![Screenshot from 2023-05-24 14-25-38](https://github.com/sirclo-solution/template-rose/assets/40454642/f6d8fd94-ecff-4359-a35d-f964799c5a75)
![Screenshot from 2023-05-24 14-25-40](https://github.com/sirclo-solution/template-rose/assets/40454642/d136aa59-ec6f-4c3b-adaa-6e597fc830aa)

Insufficient point:
![Screenshot from 2023-05-24 14-25-49](https://github.com/sirclo-solution/template-rose/assets/40454642/f968e7a3-864d-496a-a0bd-d5d3f920d9a8)
![Screenshot from 2023-05-24 14-25-50](https://github.com/sirclo-solution/template-rose/assets/40454642/d308224c-d28b-44f1-be5d-7017acbe538f)

2023-05-24 08:51 UTC, mayun19 requested changes
- Ada req dari ui/ux penambahan title “Gunakan Poin” di popup point
- Popup coupon nya aman to ?

2023-05-24 09:46 UTC, ardiankristo commented
> 

Updated screenshots:

**[ID]**
![Screenshot from 2023-05-24 16-41-17](https://github.com/sirclo-solution/template-rose/assets/40454642/11bf7387-91c1-4e74-9673-41e11809742d)
![Screenshot from 2023-05-24 16-43-43](https://github.com/sirclo-solution/template-rose/assets/40454642/3a33d099-f1ef-43cd-9fdb-c380b259e40f)

**[EN]**
![Screenshot from 2023-05-24 16-37-49](https://github.com/sirclo-solution/template-rose/assets/40454642/e53a51c4-37c4-43f0-a5b6-0cf5965f20bf)
![Screenshot from 2023-05-24 16-38-03](https://github.com/sirclo-solution/template-rose/assets/40454642/b23d60c5-7d75-4747-9066-67cd34db6e60)

Voucher aman:
![Screenshot from 2023-05-24 16-32-56](https://github.com/sirclo-solution/template-rose/assets/40454642/2dec5b6b-33a9-401e-bf15-f0a735c5842f)
![Screenshot from 2023-05-24 16-32-58](https://github.com/sirclo-solution/template-rose/assets/40454642/a3c9195a-f328-475e-b010-0730c3dec7b7)
note: desktop dari awal emang fullscreen gitu juga ya ternyata :thinking:

2023-05-25 04:42 UTC, ardiankristo commented
![Screenshot from 2023-05-25 11-42-19](https://github.com/sirclo-solution/template-rose/assets/40454642/6b46bd14-a26d-4227-a11a-8a7cb33bf45f)

2023-05-25 04:45 UTC, iqbalwijonarko approved these changes

2023-05-25 04:56 UTC, mayun19 approved these changes

2023-05-25 05:19 UTC, merged